//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hambasafe.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Invitations = new HashSet<Invitation>();
        }
    
        public int EventId { get; set; }
        public Nullable<int> StartEventLocationId { get; set; }
        public Nullable<int> EndEventLocationId { get; set; }
        public int OwnerUserId { get; set; }
        public int EventTypeId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateTimeStart { get; set; }
        public Nullable<System.DateTime> DateTimeEnd { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public short MaxWaitingMinutes { get; set; }
        public string Attributes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual EventLocation EventLocation { get; set; }
        public virtual EventLocation EventLocation1 { get; set; }
        public virtual EventType EventType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual User User { get; set; }
    }
}
