//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hambasafe.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public int InvitationId { get; set; }
        public Nullable<int> InvitorUserId { get; set; }
        public Nullable<int> InviteeUserId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string OptionalEmailInvitee { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Status { get; set; }
        public string StatusReason { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
